apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  selector:
    app: helloworld-web
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
    name: http