parameters:
- name: teardown
  displayName: Teardown Environment
  type: boolean
  default: true

trigger: 
  #batch: true
  branches:
    include:
    - main
  paths:
    include:
    - 'Infrastructure/Pipelines/*'
    - 'HelloWorld/*'

