trigger: none
pr: none # PR Trigger

resources:
  repositories:
    - repository: EnvironmentAutomation
      type: github
      name: NetworkContractSolutions/EnvironmentAutomation
      ref: refs/heads/test-agents
      endpoint: 'NetworkContractSolutions (3)'

#variables that are defined in the pipeline
  #AzureResourceManagerSC: <Name of the Azure Resource Manager service connection>
  #OctopusApiKey: 
  
stages:
- stage: CreateEnvironment
  displayName: Create Environment
  dependsOn: []
  pool:
    name: 'WindowsAgents'
    demands: TestAgentSupport
  jobs:
  - job: CreateVM
    displayName: Create VM
    steps:
    - template: 'Templates/Tasks/setup-testagent.yml@EnvironmentAutomation'
      parameters:
        AzureResourceManagerSC: '$(AzureResourceManagerSC)'
        OctopusApiKey: '$(OctopusApiKey)'
  
# - stage: Test
#   displayName: Test stage
#   dependsOn: Deploy
#   pool:
#     name: 'WindowsAgents'
#   jobs:
#   - job: RunTests
#     displayName: Run Tests
#     variables:
#       HomePageUrl: $[ stageDependencies.Deploy.Deploy.outputs['Deploy.retrieveurl.ContainerAppUrl'] ]
#     steps:
#     - script: dotnet build --configuration Debug
#       displayName: 'Build .NET 6 Application'

#     - task: VSTest@2
#       displayName: 'HelloWorld UI Tests'
#       inputs:
#         testAssemblyVer2: |
#           **/*.IntegrationTests.dll
#           !**\*TestAdapter.dll
#           !**\obj\**
#           !**\bin\**\ref\**
#         uiTests: true
#         searchFolder: '$(System.DefaultWorkingDirectory)'
#         failOnMinTestsNotRun: true
#         minimumExpectedTests: '1'
#         vstestLocationMethod: 'location'
#         vstestLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\TestAgent\Common7\IDE\Extensions\TestPlatform'
